namespace Squill.PostgresParser.Syntax;

public class IdentityColumnConstraint : ColumnConstraint
{
    public IdentityColumnConstraint(string text, bool always)
        : base(text)
    {
        Always = always;
    }

    // True for GENERATED ALWAYS AS IDENTITY; false for GENERATED BY DEFAULT AS IDENTITY.
    public bool Always { get; }
}
