namespace Squill.PostgresParser.Syntax;

public class IdentityColumnConstraint : ColumnConstraint
{
    public IdentityColumnConstraint(string text,
        bool always,
        long? startValue = null,
        long? increment = null,
        long? minValue = null,
        long? maxValue = null,
        long? cacheSize = null,
        bool? cycle = null)
        : base(text)
    {
        Always = always;
        StartValue = startValue;
        Increment = increment;
        MinValue = minValue;
        MaxValue = maxValue;
        CacheSize = cacheSize;
        Cycle = cycle;
    }

    // True for GENERATED ALWAYS AS IDENTITY; false for GENERATED BY DEFAULT AS IDENTITY.
    public bool Always { get; }

    // The parenthesized sequence options, null when not written. NO MAXVALUE and
    // NO MINVALUE select the default bounds — the same meaning as omitting the option —
    // so they read as null; NO CYCLE is Cycle = false.

    /// <summary>The START WITH value, or null when omitted.</summary>
    public long? StartValue { get; }

    /// <summary>The INCREMENT BY value, or null when omitted.</summary>
    public long? Increment { get; }

    /// <summary>The MINVALUE, or null when omitted or NO MINVALUE.</summary>
    public long? MinValue { get; }

    /// <summary>The MAXVALUE, or null when omitted or NO MAXVALUE.</summary>
    public long? MaxValue { get; }

    /// <summary>The CACHE size, or null when omitted.</summary>
    public long? CacheSize { get; }

    /// <summary>True for CYCLE, false for NO CYCLE, null when omitted.</summary>
    public bool? Cycle { get; }
}
