using Squill.Core;
using Squill.PostgresParser;

namespace Squill.Provider.Postgres.Tests;

/// <summary>
/// Identity sequence options (issue #13): the parenthesized option list on
/// GENERATED ... AS IDENTITY is modeled as column properties — but only when an option
/// differs from Postgres's default for the column's type and sequence direction, so a
/// parsed model hash-matches one extracted from the database (where information_schema
/// reports every option with defaults filled in).
/// </summary>
public class IdentitySequenceOptionsTests
{
    private static async Task<Element> IdentityColumnFor(string sql)
    {
        var workspace = new Workspace();
        workspace.Files.Add(new InMemoryStringFile("Widgets.sql", FileKind.Compile, sql));

        var model = await new ParserWorkspaceModelBuilder(workspace, new AntlrPostgresParser())
            .ExtractModelAsync(TestContext.Current.CancellationToken);

        var table = model.Elements.Single(i => i.Type == PostgresElementTypes.SqlTable);
        var columns = table.GetRelationship(PostgresRelationshipNames.Columns)!;

        return Assert.IsType<Element>(columns.Entries[0]);
    }

    [Fact]
    public async Task NonDefaultOptions_AreModeledAsProperties()
    {
        var column = await IdentityColumnFor("""
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5 MINVALUE 100 MAXVALUE 9999 CACHE 10 CYCLE)
);
""");

        Assert.Equal(100L, column.GetProperty<long?>(PostgresPropertyNames.StartValue));
        Assert.Equal(5L, column.GetProperty<long?>(PostgresPropertyNames.Increment));
        Assert.Equal(100L, column.GetProperty<long?>(PostgresPropertyNames.MinValue));
        Assert.Equal(9999L, column.GetProperty<long?>(PostgresPropertyNames.MaxValue));
        Assert.Equal(10L, column.GetProperty<long?>(PostgresPropertyNames.CacheSize));
        Assert.Equal(true, column.GetProperty<bool?>(PostgresPropertyNames.IsCycling));

        // Fixed emission order after IsIdentity/IdentityGeneration, so parser-built and
        // DB-extracted models hash identically (the Merkle hash is order-sensitive).
        var names = column.Properties.Select(p => p.Name).ToList();
        Assert.Equal(
            [
                PostgresPropertyNames.IsNullable,
                PostgresPropertyNames.IsIdentity,
                PostgresPropertyNames.IdentityGeneration,
                PostgresPropertyNames.StartValue,
                PostgresPropertyNames.Increment,
                PostgresPropertyNames.MinValue,
                PostgresPropertyNames.MaxValue,
                PostgresPropertyNames.CacheSize,
                PostgresPropertyNames.IsCycling,
            ],
            names);
    }

    [Fact]
    public async Task DefaultValuedOptions_AreOmitted()
    {
        // Every option here equals the integer identity default, so none may be stored —
        // otherwise the model would never hash-match a DB extraction of a plain identity.
        var column = await IdentityColumnFor("""
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 NO CYCLE)
);
""");

        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.StartValue));
        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.Increment));
        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.MinValue));
        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.MaxValue));
        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.CacheSize));
        Assert.Null(column.GetProperty<bool?>(PostgresPropertyNames.IsCycling));
    }

    [Fact]
    public async Task MaxValueDefault_IsTypeAware()
    {
        // 32767 is smallint's default MAXVALUE (omitted) but a non-default for integer
        // (stored) — the defaults must be computed from the column's type.
        var smallintColumn = await IdentityColumnFor("""
CREATE TABLE widgets
(
    id smallint GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 32767)
);
""");
        Assert.Null(smallintColumn.GetProperty<long?>(PostgresPropertyNames.MaxValue));

        var integerColumn = await IdentityColumnFor("""
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 32767)
);
""");
        Assert.Equal(32767L, integerColumn.GetProperty<long?>(PostgresPropertyNames.MaxValue));

        var bigintColumn = await IdentityColumnFor("""
CREATE TABLE widgets
(
    id bigint GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807)
);
""");
        Assert.Null(bigintColumn.GetProperty<long?>(PostgresPropertyNames.MaxValue));
    }

    [Fact]
    public async Task DescendingIdentity_UsesDescendingDefaults()
    {
        // For a descending sequence Postgres defaults to start = -1, minvalue = type min,
        // maxvalue = -1 — so INCREMENT BY -1 alone stores only the increment.
        var column = await IdentityColumnFor("""
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY -1 START WITH -1 MINVALUE -2147483648 MAXVALUE -1)
);
""");

        Assert.Equal(-1L, column.GetProperty<long?>(PostgresPropertyNames.Increment));
        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.StartValue));
        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.MinValue));
        Assert.Null(column.GetProperty<long?>(PostgresPropertyNames.MaxValue));
    }
}
