using Squill.Core;
using Squill.PostgresParser;

namespace Squill.Provider.Postgres.Tests;

/// <summary>
/// Fast, Docker-free tests over the pure model-to-SQL generation. Input models are
/// built with the parser-based model builder (no database required) and diffed
/// against an empty target so every element becomes a CreateDelta.
/// </summary>
public class PostgresScriptGeneratorTests
{
    private static async Task<SchemaComparison> CompareToEmptyAsync(string sql)
    {
        var parser = new AntlrPostgresParser();
        var workspace = new Workspace();
        workspace.Files.Add(new InMemoryStringFile("Test.sql", FileKind.Compile, sql));

        var model = await new ParserWorkspaceModelBuilder(workspace, parser).ExtractModelAsync();

        var provider = new PostgresDatabaseProvider("Host=unused");
        return SchemaCompare.Compare(provider, model, new Model());
    }

    [Fact]
    public async Task GenerateScript_CreateTable()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE film
(
    film_id integer PRIMARY KEY,
    title   varchar(255) NOT NULL
);
""");

        var generator = new PostgresScriptGenerator();

        var sql = generator.GenerateScript(comparison);

        Assert.Contains("CREATE TABLE \"film\"", sql);
        Assert.Contains("NOT NULL", sql);
        Assert.Contains("varchar(255)", sql);
        // The parser now emits the PK as a first-class element, so it scripts.
        Assert.Contains("PRIMARY KEY", sql);
    }

    [Fact]
    public async Task GenerateScript_BareVarchar_ScriptsWithoutLengthOrMax()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE notes
(
    body varchar
);
""");

        var generator = new PostgresScriptGenerator();

        var sql = generator.GenerateScript(comparison);

        // A length-less varchar must script as plain `varchar`; `varchar(MAX)` is
        // SQL-Server syntax and is not valid Postgres.
        Assert.Contains("varchar", sql);
        Assert.DoesNotContain("MAX", sql);
        Assert.DoesNotContain("varchar(", sql);
    }

    [Fact]
    public async Task GenerateScript_CreateTableWithIndex()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE film
(
    film_id integer PRIMARY KEY,
    title   varchar(255) NOT NULL
);

CREATE INDEX idx_film_title ON film (title);
""");

        var generator = new PostgresScriptGenerator();

        var sql = generator.GenerateScript(comparison);

        Assert.Contains("CREATE INDEX \"idx_film_title\" ON \"film\"", sql);
        Assert.Contains("(\"title\")", sql);
    }

    [Fact]
    public async Task GenerateScript_PartialIndex_EmitsWhereClause()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE users
(
    id    integer PRIMARY KEY,
    email varchar(255)
);

CREATE INDEX idx_users_email ON users (email) WHERE email IS NOT NULL;
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.Contains("CREATE INDEX \"idx_users_email\" ON \"users\"", sql);
        Assert.Contains("(\"email\")", sql);
        Assert.Contains("WHERE \"email\" IS NOT NULL", sql);
    }

    [Fact]
    public async Task GenerateScript_PartialIndex_WithComparisonPredicate()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE orders
(
    id          integer PRIMARY KEY,
    customer_id integer NOT NULL,
    status      varchar(20) NOT NULL
);

CREATE INDEX idx_active_orders ON orders (customer_id) WHERE status = 'active';
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.Contains("CREATE INDEX \"idx_active_orders\" ON \"orders\"", sql);
        Assert.Contains("WHERE \"status\" = 'active'", sql);
    }

    [Fact]
    public async Task GenerateScript_FullIndex_HasNoWhereClause()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE film
(
    film_id integer PRIMARY KEY,
    title   varchar(255) NOT NULL
);

CREATE INDEX idx_film_title ON film (title);
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.DoesNotContain("WHERE", sql);
    }

    [Fact]
    public async Task GenerateScript_IdentityColumns()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE widgets
(
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_no integer GENERATED ALWAYS AS IDENTITY
);
""");

        var generator = new PostgresScriptGenerator();

        var sql = generator.GenerateScript(comparison);

        Assert.Contains("\"id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql);
        Assert.Contains("\"serial_no\" integer GENERATED ALWAYS AS IDENTITY", sql);
        // Identity columns must not carry an explicit NULL/NOT NULL suffix.
        Assert.DoesNotContain("GENERATED ALWAYS AS IDENTITY NULL", sql);
        Assert.DoesNotContain("GENERATED ALWAYS AS IDENTITY NOT NULL", sql);
    }

    [Fact]
    public async Task GenerateScript_MultiColumnPrimaryKey_EmitsTableLevelClause()
    {
        // The parser now understands table-level PRIMARY KEY (a, b) (issue #7), so the
        // model is built straight from SQL like the other cases.
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE enrollment
(
    student_id integer NOT NULL,
    course_id  integer NOT NULL,
    PRIMARY KEY (student_id, course_id)
);
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        // Multi-column PK must be a table-level clause, not inline on a single column.
        Assert.DoesNotContain("integer PRIMARY KEY", sql);
        // An unnamed table-level PK gets the Postgres <table>_pkey constraint name.
        Assert.Contains("CONSTRAINT \"enrollment_pkey\" PRIMARY KEY (\"student_id\", \"course_id\")", sql);
    }

    [Fact]
    public async Task GenerateScript_NamedMultiColumnPrimaryKey_EmitsConstraintName()
    {
        // A table-level PRIMARY KEY named with CONSTRAINT must keep that name when
        // scripted, so the constraint lands in the database with the intended name.
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE enrollment
(
    student_id integer NOT NULL,
    course_id  integer NOT NULL,
    CONSTRAINT pk_enrollment PRIMARY KEY (student_id, course_id)
);
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.Contains("CONSTRAINT \"pk_enrollment\" PRIMARY KEY (\"student_id\", \"course_id\")", sql);
    }

    [Fact]
    public async Task GenerateScript_UniqueIndexWithMethodAndDirection()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE account
(
    account_id integer PRIMARY KEY,
    email      varchar(255) NOT NULL
);

CREATE UNIQUE INDEX idx_account_email ON account USING btree (email DESC NULLS LAST);
""");

        var generator = new PostgresScriptGenerator();

        var sql = generator.GenerateScript(comparison);

        Assert.Contains("CREATE UNIQUE INDEX \"idx_account_email\" ON \"account\" USING btree", sql);
        Assert.Contains("\"email\" DESC NULLS LAST", sql);
    }

    [Fact]
    public async Task GenerateScript_InlineForeignKeyWithOnDeleteCascade()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE customers
(
    id integer PRIMARY KEY
);

CREATE TABLE orders
(
    id          integer PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id) ON DELETE CASCADE
);
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.Contains(
            "CONSTRAINT \"orders_customer_id_fkey\" FOREIGN KEY (\"customer_id\") REFERENCES \"customers\" (\"id\") ON DELETE CASCADE",
            sql);
    }

    [Fact]
    public async Task GenerateScript_TableLevelCompositeForeignKey()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE orders
(
    id      integer NOT NULL,
    line_no integer NOT NULL,
    PRIMARY KEY (id, line_no)
);

CREATE TABLE order_lines
(
    order_id integer NOT NULL,
    line_no  integer NOT NULL,
    CONSTRAINT fk_lines FOREIGN KEY (order_id, line_no) REFERENCES orders (id, line_no) ON DELETE CASCADE ON UPDATE RESTRICT
);
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.Contains(
            "CONSTRAINT \"fk_lines\" FOREIGN KEY (\"order_id\", \"line_no\") REFERENCES \"orders\" (\"id\", \"line_no\") ON DELETE CASCADE ON UPDATE RESTRICT",
            sql);
    }

    [Fact]
    public async Task GenerateScript_CreateExtension()
    {
        var comparison = await CompareToEmptyAsync("CREATE EXTENSION citext;");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        // IF NOT EXISTS keeps publish idempotent for an already-installed extension.
        Assert.Contains("CREATE EXTENSION IF NOT EXISTS \"citext\";", sql);
    }

    [Fact]
    public async Task GenerateScript_CreateExtensionWithVersion()
    {
        var comparison = await CompareToEmptyAsync("CREATE EXTENSION citext WITH VERSION '1.6';");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.Contains("CREATE EXTENSION IF NOT EXISTS \"citext\" VERSION '1.6';", sql);
    }

    [Fact]
    public async Task GenerateScript_VectorColumn_ScriptsWithDimension()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE items
(
    id        integer PRIMARY KEY,
    embedding vector(3)
);
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        // The dimension modifier must be preserved in the emitted column definition.
        Assert.Contains("\"embedding\" vector(3)", sql);
    }

    [Fact]
    public async Task GenerateScript_HnswIndex_EmitsOperatorClassAndStorageParameters()
    {
        var comparison = await CompareToEmptyAsync("""
CREATE TABLE items
(
    id        integer PRIMARY KEY,
    embedding vector(3)
);

CREATE INDEX items_embedding_idx ON items USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
""");

        var sql = new PostgresScriptGenerator().GenerateScript(comparison);

        Assert.Contains("USING hnsw", sql);
        Assert.Contains("(\"embedding\" vector_cosine_ops)", sql);
        Assert.Contains("WITH (m=16, ef_construction=64)", sql);
    }
}
