using Squill.Core;
using Squill.Provider.Postgres;

namespace Squill.IntegrationTests.Postgres.IdentityTest;

public class PostgresIdentityTest : PostgresIntegrationTestBase
{
    // Full round trip for identity columns: build a model from SQL against a temporary
    // database, publish it into a fresh target, re-extract, and assert the identity
    // properties survive and the model hashes match. Exercises identity script
    // generation and extraction (is_identity / identity_generation) — for both
    // GENERATED BY DEFAULT and GENERATED ALWAYS — against a real Postgres database.
    [Fact]
    public async Task IdentityColumnRoundTrip_ModelHashesMatchAfterPublish()
    {
        IDatabaseProvider provider = new PostgresDatabaseProvider(ConnectionString);

        var workspace = new Workspace();
        workspace.Files.Add(new EmbeddedResourceFile(
            "Squill.IntegrationTests.Postgres.IdentityTest.TableWithIdentity.sql", FileKind.Compile));

        var model = await new TemporaryDatabaseModelBuilder(provider)
            .BuildModelAsync(workspace, TestContext.Current.CancellationToken);

        AssertIdentityColumns(model);

        var testDb = await provider.CreateDatabaseAsync(
            $"squill_test_{Guid.NewGuid():n}", TestContext.Current.CancellationToken);
        var dbModelBuilder = provider.CreateDatabaseModelBuilder(testDb);

        try
        {
            var emptyModel = await dbModelBuilder.ExtractModelAsync(TestContext.Current.CancellationToken);

            var comparison = SchemaCompare.Compare(provider, model, emptyModel);

            await testDb.PublishAsync(comparison, TestContext.Current.CancellationToken);

            var publishedModel = await dbModelBuilder.ExtractModelAsync(TestContext.Current.CancellationToken);

            AssertIdentityColumns(publishedModel);

            Assert.True(HashUtility.HashesEqual(model.Hash, publishedModel.Hash), "Model hashes do not match");
        }
        finally
        {
            await testDb.DropAsync(TestContext.Current.CancellationToken);
        }
    }

    private static void AssertIdentityColumns(Model model)
    {
        var table = model.Elements.Single(i => i.Type == PostgresElementTypes.SqlTable);
        var columns = table.GetRelationship(PostgresRelationshipNames.Columns)!;

        var idColumn = columns.Entries.OfType<Element>().Single(c => c.Name as string == "widgets.id");
        Assert.Equal(true, idColumn.GetProperty<bool?>(PostgresPropertyNames.IsIdentity));
        Assert.Equal("ByDefault", idColumn.GetProperty<string>(PostgresPropertyNames.IdentityGeneration));

        var serialColumn = columns.Entries.OfType<Element>().Single(c => c.Name as string == "widgets.serial_no");
        Assert.Equal(true, serialColumn.GetProperty<bool?>(PostgresPropertyNames.IsIdentity));
        Assert.Equal("Always", serialColumn.GetProperty<string>(PostgresPropertyNames.IdentityGeneration));

        var nameColumn = columns.Entries.OfType<Element>().Single(c => c.Name as string == "widgets.name");
        Assert.Null(nameColumn.GetProperty<bool?>(PostgresPropertyNames.IsIdentity));
    }
}
