using System.Text;
using Squill.Core;
using Squill.PostgresParser.Syntax;

namespace Squill.Provider.Postgres;

/// <summary>
/// Generates PostgreSQL DDL from schema deltas. This is pure model-to-SQL logic
/// with no database dependency, so it can be unit-tested without a live server.
/// </summary>
public class PostgresScriptGenerator
{
    /// <summary>
    /// Generates a single script covering every delta in the comparison, in order.
    /// </summary>
    public string GenerateScript(SchemaComparison comparison)
    {
        var sb = new StringBuilder();

        foreach (var delta in comparison.Deltas)
        {
            sb.Append(GenerateScriptForDelta(delta));
        }

        return sb.ToString();
    }

    public string GenerateScriptForDelta(SchemaDelta delta)
    {
        if (delta is CreateDelta createDelta)
        {
            return GenerateCreateScript(createDelta);
        }

        throw new NotImplementedException();
    }

    private string GenerateCreateScript(CreateDelta createDelta)
    {
        if (createDelta.Element.Type == PostgresElementTypes.SqlTable)
        {
            return GenerateCreateTableScript(createDelta.Element, createDelta.DependentElements);
        }

        throw new NotImplementedException();
    }

    private string GenerateCreateTableScript(Element table, IList<Element> dependentElements)
    {
        if (table.Name is not string tableName)
        {
            throw new ArgumentException("Tables must have names");
        }

        // Stored names are canonical/unquoted; quote when emitting SQL.
        var quotedTableName = SqlName.Parse(tableName).Sql;

        var sb = new StringBuilder();

        sb.Append("CREATE TABLE ").Append(quotedTableName).AppendLine("");
        sb.AppendLine("(");

        var columnText = new List<string>();

        var pk = dependentElements.SingleOrDefault(i => i.Type == PostgresElementTypes.SqlPrimaryKeyConstraint);

        var pkColumns = pk == null ? new List<string>() : GetPrimaryKeyColumns(pk);

        foreach (var columnRelationship in table.Relationships.Where(i => i.Name == PostgresRelationshipNames.Columns))
        {
            foreach (var column in columnRelationship.Entries.OfType<Element>().Where(i => i.Type == PostgresElementTypes.SqlSimpleColumn))
            {
                if (column.Name is not string columnName)
                {
                    throw new InvalidOperationException("Missing column name");
                }

                var columnType = GetTypeStringForColumn(column);

                // The stored column Name is table-qualified (e.g. film.title); a column
                // definition needs just the bare, quoted identifier.
                var text = $"\"{SqlName.UnqualifiedOf(columnName)}\" {columnType}";

                var isIdentity = column.GetProperty<bool?>(PostgresPropertyNames.IsIdentity) == true;
                var isSingleColumnPk = pkColumns.Count == 1 && pkColumns[0].Equals(columnName);

                if (isIdentity)
                {
                    // Identity columns are implicitly NOT NULL; Postgres rejects an
                    // explicit NULL and does not need a redundant NOT NULL, so no
                    // nullability suffix is emitted for identity columns.
                    var generation = column.GetProperty<string>(PostgresPropertyNames.IdentityGeneration);

                    text += generation == "Always"
                        ? " GENERATED ALWAYS AS IDENTITY"
                        : " GENERATED BY DEFAULT AS IDENTITY";
                }

                // A single-column PK is written inline; a composite PK is emitted as a
                // table-level clause below.
                if (isSingleColumnPk)
                {
                    // TODO: support named PK constraints
                    text += " PRIMARY KEY";
                }
                else if (!isIdentity)
                {
                    var nullable = column.GetProperty<bool?>(PostgresPropertyNames.IsNullable);

                    text += nullable == false ? " NOT NULL" : " NULL";
                }

                columnText.Add(text);
            }
        }

        if (pkColumns.Count > 1)
        {
            var pkColumnList = string.Join(", ", pkColumns.Select(c => $"\"{SqlName.UnqualifiedOf(c)}\""));
            columnText.Add($"PRIMARY KEY ({pkColumnList})");
        }

        foreach (var foreignKey in dependentElements.Where(i => i.Type == PostgresElementTypes.SqlForeignKeyConstraint))
        {
            columnText.Add(GetForeignKeyClause(foreignKey));
        }

        sb.Append("    ").AppendLine(string.Join($",{Environment.NewLine}    ", columnText));

        sb.AppendLine(");");

        foreach (var index in dependentElements.Where(i => i.Type == PostgresElementTypes.SqlIndex))
        {
            sb.AppendLine();
            sb.Append(GenerateCreateIndexScript(index, quotedTableName));
        }

        return sb.ToString();
    }

    private static string GenerateCreateIndexScript(Element index, string quotedTableName)
    {
        if (index.Name is not string indexName)
        {
            throw new ArgumentException("Indexes must have names");
        }

        // CREATE INDEX <name> ON <table>: the index name is bare (its schema is the
        // table's), so emit just the quoted final segment.
        var quotedIndexName = SqlName.Parse(indexName).QuotedUnqualified;

        var isUnique = index.GetProperty<bool?>(PostgresPropertyNames.IsUnique) == true;
        var indexMethod = index.GetProperty<string>(PostgresPropertyNames.IndexMethod);

        var columnSpecs = index.GetRelationship(PostgresRelationshipNames.ColumnSpecifications);

        if (columnSpecs == null)
        {
            throw new InvalidOperationException($"Index {indexName} has no column specifications");
        }

        var columnText = new List<string>();

        foreach (var columnSpec in columnSpecs.Entries.OfType<Element>()
                     .Where(i => i.Type == PostgresElementTypes.SqlIndexedColumnSpecification))
        {
            var columnReference = columnSpec.GetRelationship(PostgresRelationshipNames.Column)
                ?.Entries.OfType<Reference>().SingleOrDefault();

            if (columnReference == null)
            {
                throw new InvalidOperationException($"Index {indexName} column specification has no column reference");
            }

            // Column references are stored table-qualified (e.g. film.title); the
            // CREATE INDEX column list needs just the bare, quoted column name.
            var text = $"\"{SqlName.UnqualifiedOf(columnReference.Name)}\"";

            if (columnSpec.GetProperty<bool?>(PostgresPropertyNames.IsAscending) == false)
            {
                text += " DESC";
            }

            if (columnSpec.GetProperty<bool?>(PostgresPropertyNames.NullsFirst) is bool nullsFirst)
            {
                text += nullsFirst ? " NULLS FIRST" : " NULLS LAST";
            }

            columnText.Add(text);
        }

        var sb = new StringBuilder();

        sb.Append("CREATE ");

        if (isUnique)
        {
            sb.Append("UNIQUE ");
        }

        sb.Append("INDEX ").Append(quotedIndexName).Append(" ON ").Append(quotedTableName);

        if (indexMethod != null)
        {
            sb.Append(" USING ").Append(indexMethod);
        }

        sb.Append(" (").Append(string.Join(", ", columnText)).AppendLine(");");

        return sb.ToString();
    }

    // CONSTRAINT "<name>" FOREIGN KEY ("a", "b") REFERENCES "table" ("x", "y")
    //   [ON DELETE <action>] [ON UPDATE <action>]
    private static string GetForeignKeyClause(Element foreignKey)
    {
        if (foreignKey.Name is not string fkName)
        {
            throw new ArgumentException("Foreign keys must have names");
        }

        var columns = GetReferenceColumnNames(foreignKey, PostgresRelationshipNames.ForeignKeyColumns);

        if (columns.Count == 0)
        {
            throw new InvalidOperationException($"Foreign key {fkName} has no referencing columns");
        }

        var foreignTableRef = foreignKey.GetRelationship(PostgresRelationshipNames.ForeignTable)
            ?.Entries.OfType<Reference>().SingleOrDefault();

        if (foreignTableRef == null)
        {
            throw new InvalidOperationException($"Foreign key {fkName} has no referenced table");
        }

        var foreignColumns = GetReferenceColumnNames(foreignKey, PostgresRelationshipNames.ForeignColumns);

        var sb = new StringBuilder();

        sb.Append("CONSTRAINT ").Append(SqlName.Parse(fkName).QuotedUnqualified)
            .Append(" FOREIGN KEY (")
            .Append(string.Join(", ", columns.Select(c => $"\"{c}\"")))
            .Append(") REFERENCES ")
            .Append(SqlName.Parse(foreignTableRef.Name).QuotedUnqualified);

        if (foreignColumns.Count > 0)
        {
            sb.Append(" (").Append(string.Join(", ", foreignColumns.Select(c => $"\"{c}\""))).Append(')');
        }

        var deleteAction = foreignKey.GetProperty<string>(PostgresPropertyNames.DeleteAction);
        if (deleteAction != null)
        {
            sb.Append(" ON DELETE ").Append(RenderReferentialAction(deleteAction));
        }

        var updateAction = foreignKey.GetProperty<string>(PostgresPropertyNames.UpdateAction);
        if (updateAction != null)
        {
            sb.Append(" ON UPDATE ").Append(RenderReferentialAction(updateAction));
        }

        return sb.ToString();
    }

    // References store table-qualified names (e.g. orders.customer_id); a constraint
    // clause needs just the bare column identifiers, in order.
    private static IList<string> GetReferenceColumnNames(Element element, string relationshipName)
    {
        var relationship = element.GetRelationship(relationshipName);

        if (relationship == null)
        {
            return new List<string>();
        }

        return relationship.Entries
            .OfType<Reference>()
            .Select(r => SqlName.UnqualifiedOf(r.Name))
            .ToList();
    }

    private static string RenderReferentialAction(string action)
        => Enum.Parse<ReferentialAction>(action) switch
        {
            ReferentialAction.NoAction => "NO ACTION",
            ReferentialAction.Restrict => "RESTRICT",
            ReferentialAction.Cascade => "CASCADE",
            ReferentialAction.SetNull => "SET NULL",
            ReferentialAction.SetDefault => "SET DEFAULT",
            _ => throw new InvalidOperationException($"Unknown referential action: {action}"),
        };

    private static IList<string> GetPrimaryKeyColumns(Element pkConstraint)
    {
        var columnSpecs = pkConstraint.GetRelationship(PostgresRelationshipNames.ColumnSpecifications);

        if (columnSpecs == null)
        {
            return new List<string>();
        }

        var columns = new List<string>();

        foreach (var indexedColumn in columnSpecs.Entries.OfType<Element>()
                     .Where(i => i.Type == PostgresElementTypes.SqlIndexedColumnSpecification))
        {
            var column = indexedColumn
                .GetRelationship(PostgresRelationshipNames.Column)
                ?.Entries
                .OfType<Reference>()
                .SingleOrDefault();

            if (column == null)
            {
                throw new InvalidOperationException(
                    "Primary key column specification has no column reference");
            }

            columns.Add(column.Name);
        }

        return columns;
    }

    private string GetTypeStringForColumn(Element column)
    {
        // HACK.PI: assume there's a type specifier and built-in type reference
        var typeSpecifier = column.Relationships.Single(i => i.Name == PostgresRelationshipNames.TypeSpecifier);

        var typeElement = typeSpecifier.Entries
            .OfType<Element>()
            .Single(i => i.Type == PostgresElementTypes.SqlTypeSpecifier);

        var type = typeElement.Relationships.Single(i => i.Name == PostgresRelationshipNames.Type);

        var typeReference = type.Entries
            .OfType<Reference>()
            .Single();

        var maxLength = typeElement.GetProperty<int?>(PostgresPropertyNames.Length);

        return typeReference.Name.ToLower() switch
        {
            "varchar" or "nvarchar" => $"{typeReference.Name}({(maxLength != null ? maxLength : "MAX")})",
            "character varying" => $"varchar({(maxLength != null ? maxLength : "MAX")})",
            _ => typeReference.Name,
        };
    }
}
