<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>nullable</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Antlr4.Runtime.Standard" Version="4.11.1" />
        <PackageReference Include="Npgsql" Version="7.0.0" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Squill.Core\Squill.Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <None Include="AntlrParser\PostgreSQLLexer.g4" />
      <None Include="AntlrParser\PostgreSQLParser.g4" />
    </ItemGroup>
    
</Project>
