using Npgsql;
using Squill.Core;
using Squill.Dacpac;
using Squill.PostgresParser;
using Squill.Provider.Postgres;

namespace Squill.IntegrationTests.Postgres.IdentityAlterTest;

// End-to-end coverage (issue #137) for changing a column's identity definition on a table that
// already holds data, against real Postgres: deploy schema A, seed rows, deploy schema B to the
// same database, and assert the rows survive with their values intact and the identity actually
// changed in the catalog.
//
// The mechanism under test is deliberately recorded, not just the outcome.
// PostgresTableDiffAnalyzer.ColumnChangeRequiresRebuild returns IdentityDiffers(...), so EVERY
// identity change — adding identity, dropping it, flipping ALWAYS to BY DEFAULT, or merely
// bumping the increment — takes the FULL TABLE REBUILD path (rename aside, recreate, copy rows,
// drop the original) rather than the one-line ALTER COLUMN ... ADD/DROP IDENTITY / SET INCREMENT
// BY that Postgres supports. Squill's standalone-sequence path already does the in-place trick
// (Sequence_ChangedOption_AltersInPlaceAndPreservesCurrentValue in PostgresSequenceTest); the
// column path does not. Each test below asserts whether a rebuild happened by looking for the
// aside-rename in the generated script, so the cost is quantified and a future in-place
// optimization has an explicit expectation to flip.
//
// No DeployOptions override is needed anywhere here: an identity rebuild drops no columns, so it
// is lossless and deploys under the default data-loss guard (same reasoning as the comment at the
// end of InsertColumnBetweenExisting_RebuildsTable_AndPreservesData in PostgresAlterTableTest).
public class PostgresIdentityAlterTest : PostgresIntegrationTestBase
{
    /// <summary>
    /// Adding GENERATED BY DEFAULT AS IDENTITY to a plain integer column. Postgres can do this
    /// with ALTER TABLE ... ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; Squill instead
    /// REBUILDS THE WHOLE TABLE (asserted below). The interesting risk is the freshly created
    /// identity sequence: the rebuild copies the existing ids verbatim, so unless the sequence is
    /// advanced past them the next generated key collides with a copied row.
    /// </summary>
    [Fact]
    public async Task AddIdentityToExistingColumn_RebuildsTable_AndPreservesDataAndAdvancesSequence()
    {
        const string before = """
CREATE TABLE people
(
    id   integer PRIMARY KEY,
    name text NOT NULL
);
""";
        const string after = """
CREATE TABLE people
(
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
""";

        await RunDeployScenarioAsync(
            before, after,
            seedSql: "INSERT INTO people (id, name) VALUES (1, 'alice'), (2, 'bob');",
            assertAfterAsync: async (conn, script) =>
            {
                // Recorded, not endorsed: adding identity takes the rebuild path.
                AssertRebuilt(script, rebuilt: true);

                // Both seeded rows survive with their original keys and values.
                Assert.Equal(2L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
                Assert.Equal("alice", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 1;"));
                Assert.Equal("bob", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 2;"));

                // The column is now a BY DEFAULT identity ('d'; 'a' would be ALWAYS, '' none).
                Assert.Equal("d", await AttidentityAsync(conn, "people", "id"));

                // The newly created identity sequence must have been advanced past the copied
                // ids, or this insert would collide with id = 1.
                await ExecuteAsync(conn, "INSERT INTO people (name) VALUES ('carol');",
                    TestContext.Current.CancellationToken);

                Assert.Equal(3, await ScalarAsync(conn, "SELECT id FROM people WHERE name = 'carol';"));
                Assert.Equal(3L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
            });
    }

    /// <summary>
    /// The reverse: dropping identity from a column, which Postgres expresses as ALTER COLUMN ...
    /// DROP IDENTITY. Squill rebuilds instead. Afterwards the column is a plain integer, so an
    /// insert must supply the key itself.
    /// </summary>
    [Fact]
    public async Task DropIdentityFromColumn_RebuildsTable_AndPreservesData()
    {
        const string before = """
CREATE TABLE people
(
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
""";
        const string after = """
CREATE TABLE people
(
    id   integer PRIMARY KEY,
    name text NOT NULL
);
""";

        await RunDeployScenarioAsync(
            before, after,
            seedSql: "INSERT INTO people (name) VALUES ('alice'), ('bob');",
            assertAfterAsync: async (conn, script) =>
            {
                AssertRebuilt(script, rebuilt: true);

                Assert.Equal(2L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
                Assert.Equal("alice", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 1;"));
                Assert.Equal("bob", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 2;"));

                // No identity left on the column, and no default in its place either.
                Assert.Equal("", await AttidentityAsync(conn, "people", "id"));
                Assert.Null(await ColumnDefaultAsync(conn, "people", "id"));

                // With identity gone the caller supplies the key.
                await ExecuteAsync(conn, "INSERT INTO people (id, name) VALUES (3, 'carol');",
                    TestContext.Current.CancellationToken);
                Assert.Equal(3L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
            });
    }

    /// <summary>
    /// Flipping GENERATED ALWAYS to GENERATED BY DEFAULT — a pure metadata change Postgres does
    /// with ALTER COLUMN ... SET GENERATED BY DEFAULT. Squill rebuilds. The user-visible effect
    /// is that an explicit id becomes accepted where ALWAYS would have rejected it.
    /// </summary>
    [Fact]
    public async Task ChangeIdentityGeneration_AlwaysToByDefault_RebuildsTable_AndPreservesData()
    {
        const string before = """
CREATE TABLE people
(
    id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
""";
        const string after = """
CREATE TABLE people
(
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
""";

        await RunDeployScenarioAsync(
            before, after,
            seedSql: "INSERT INTO people (name) VALUES ('alice'), ('bob');",
            assertAfterAsync: async (conn, script) =>
            {
                AssertRebuilt(script, rebuilt: true);

                Assert.Equal(2L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
                Assert.Equal("alice", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 1;"));
                Assert.Equal("bob", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 2;"));

                // 'a' (ALWAYS) must have become 'd' (BY DEFAULT).
                Assert.Equal("d", await AttidentityAsync(conn, "people", "id"));

                // BY DEFAULT accepts an explicit key, which ALWAYS would have rejected.
                await ExecuteAsync(conn, "INSERT INTO people (id, name) VALUES (50, 'carol');",
                    TestContext.Current.CancellationToken);
                Assert.Equal(50, await ScalarAsync(conn, "SELECT id FROM people WHERE name = 'carol';"));

                // And generated keys still work, continuing past the copied rows.
                await ExecuteAsync(conn, "INSERT INTO people (name) VALUES ('dave');",
                    TestContext.Current.CancellationToken);
                Assert.Equal(3, await ScalarAsync(conn, "SELECT id FROM people WHERE name = 'dave';"));
            });
    }

    /// <summary>
    /// Bumping only the identity sequence's INCREMENT BY. This is the most wasteful case in the
    /// batch and the strongest argument for teaching the column path the in-place trick: Postgres
    /// would do it with a single ALTER TABLE ... ALTER COLUMN id SET INCREMENT BY 2, touching no
    /// heap data at all, but Squill COPIES EVERY ROW OF THE TABLE (asserted below). The behaviour
    /// is correct and lossless; the cost is O(table size) for a catalog-only change.
    /// </summary>
    [Fact]
    public async Task ChangeIdentitySequenceOption_RebuildsWholeTable_ForACatalogOnlyChange()
    {
        const string before = """
CREATE TABLE people
(
    id   integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MAXVALUE 1000) PRIMARY KEY,
    name text NOT NULL
);
""";
        const string after = """
CREATE TABLE people
(
    id   integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 2 MAXVALUE 1000) PRIMARY KEY,
    name text NOT NULL
);
""";

        await RunDeployScenarioAsync(
            before, after,
            seedSql: "INSERT INTO people (name) VALUES ('alice'), ('bob');",
            assertAfterAsync: async (conn, script) =>
            {
                // The finding: a pure sequence-option change rebuilds the entire table.
                AssertRebuilt(script, rebuilt: true);

                Assert.Equal(2L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
                Assert.Equal("alice", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 1;"));
                Assert.Equal("bob", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 2;"));

                // The owned sequence really carries the new increment and the old maximum.
                var (increment, max) = await OwnedSequenceOptionsAsync(conn, "people", "id");
                Assert.Equal(2L, increment);
                Assert.Equal(1000L, max);

                // Still identity, and the sequence was advanced past the copied ids — the next
                // generated key steps by the new increment from the copied maximum.
                Assert.Equal("d", await AttidentityAsync(conn, "people", "id"));

                await ExecuteAsync(conn, "INSERT INTO people (name) VALUES ('carol');",
                    TestContext.Current.CancellationToken);
                Assert.Equal(4, await ScalarAsync(conn, "SELECT id FROM people WHERE name = 'carol';"));
            });
    }

    /// <summary>
    /// A serial column redeclared as the equivalent identity column. Squill lowers serial to an
    /// identity column in the model (see SerialColumn_RoundTripsAsIdentityOverUnderlyingType in
    /// PostgresUniqueAndSerialTest), so the two schemas produce the same model and the deploy is a
    /// NO-OP — no deltas, no script. That is asserted here, together with the fact that the
    /// database is genuinely consistent with what the model claims: an identity column with no
    /// nextval default, which is what a serial declaration was lowered into on the first deploy.
    /// </summary>
    [Fact]
    public async Task SerialToIdentity_IsANoOp_AndTheDatabaseMatchesTheModel()
    {
        const string before = """
CREATE TABLE people
(
    id   serial PRIMARY KEY,
    name text NOT NULL
);
""";
        const string after = """
CREATE TABLE people
(
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
""";

        await RunDeployScenarioAsync(
            before, after,
            seedSql: "INSERT INTO people (name) VALUES ('alice'), ('bob');",
            expectChanges: false,
            assertAfterAsync: async (conn, script) =>
            {
                // Nothing to do: serial and the identity spelling describe the same column, so
                // nothing was rebuilt and nothing was scripted.
                AssertRebuilt(script, rebuilt: false);
                Assert.True(string.IsNullOrWhiteSpace(script),
                    $"serial -> identity should produce no deltas at all, but scripted: {script}");

                Assert.Equal(2L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));

                // The database agrees with the model rather than merely hash-matching it: the
                // first deploy already turned `serial` into a BY DEFAULT identity column, so
                // there is no leftover nextval() default and no separately-owned sequence with a
                // life of its own.
                Assert.Equal("d", await AttidentityAsync(conn, "people", "id"));
                Assert.Null(await ColumnDefaultAsync(conn, "people", "id"));

                // The identity's implicit sequence exists and is reachable, and the column still
                // auto-populates as a serial column would have.
                var sequence = (string?)await ScalarAsync(
                    conn, "SELECT pg_get_serial_sequence('people', 'id');");
                Assert.NotNull(sequence);

                await ExecuteAsync(conn, "INSERT INTO people (name) VALUES ('carol');",
                    TestContext.Current.CancellationToken);
                Assert.Equal(3, await ScalarAsync(conn, "SELECT id FROM people WHERE name = 'carol';"));
            });
    }

    /// <summary>
    /// Widening serial to bigserial: since both lower to identity columns, this is really an
    /// integer-to-bigint type change on an identity column. The keys must survive and a fresh
    /// insert must not collide with them.
    /// </summary>
    [Fact]
    public async Task WidenSerialColumnType_PreservesDataAndKeepsGeneratingFreshKeys()
    {
        const string before = """
CREATE TABLE people
(
    id   serial PRIMARY KEY,
    name text NOT NULL
);
""";
        const string after = """
CREATE TABLE people
(
    id   bigserial PRIMARY KEY,
    name text NOT NULL
);
""";

        await RunDeployScenarioAsync(
            before, after,
            seedSql: "INSERT INTO people (name) VALUES ('alice'), ('bob');",
            assertAfterAsync: async (conn, script) =>
            {
                Assert.Equal(2L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
                Assert.Equal("alice", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 1;"));
                Assert.Equal("bob", await ScalarAsync(conn, "SELECT name FROM people WHERE id = 2;"));

                var dataType = (string?)await ScalarAsync(conn, """
SELECT data_type FROM information_schema.columns
WHERE table_name = 'people' AND column_name = 'id';
""");
                Assert.Equal("bigint", dataType);

                // Still an identity column after the widening.
                Assert.Equal("d", await AttidentityAsync(conn, "people", "id"));

                // And the sequence is past the retained keys, so no collision.
                await ExecuteAsync(conn, "INSERT INTO people (name) VALUES ('carol');",
                    TestContext.Current.CancellationToken);
                Assert.Equal(3L, await ScalarAsync(conn, "SELECT id FROM people WHERE name = 'carol';"));
                Assert.Equal(3L, await ScalarAsync(conn, "SELECT count(*) FROM people;"));
            });
    }

    // A rebuild renames the table aside before recreating it, so the aside-rename in the
    // generated script is a reliable detector of which path the deploy took. This is recorded
    // per scenario so the cost of the current identity-change strategy is explicit.
    private static void AssertRebuilt(string script, bool rebuilt)
    {
        var sawRename = script.Contains("RENAME TO", StringComparison.OrdinalIgnoreCase);

        Assert.True(sawRename == rebuilt,
            rebuilt
                ? $"Expected a table rebuild (aside rename) but the script had none:\n{script}"
                : $"Expected no table rebuild but the script renamed the table aside:\n{script}");
    }

    // Deploys `before`, seeds data, deploys `after` to the same database, then runs the caller's
    // assertions against the final database and the generated script. Verifies the database's
    // model matches the `after` DACPAC's model along the way.
    private async Task RunDeployScenarioAsync(
        string before,
        string after,
        string seedSql,
        Func<NpgsqlConnection, string, Task> assertAfterAsync,
        bool expectChanges = true,
        DeployOptions? afterOptions = null)
    {
        var ct = TestContext.Current.CancellationToken;
        var tempDir = Directory.CreateTempSubdirectory("squill-identity-alter-integration");

        try
        {
            IDatabaseProvider provider = new PostgresDatabaseProvider(ConnectionString);
            var targetDbName = $"squill_identity_alter_{Guid.NewGuid():n}";
            var createdDb = await provider.CreateDatabaseAsync(targetDbName, ct);

            try
            {
                // Deploy the initial schema.
                var beforeDacpac = await BuildDacpacAsync(tempDir.FullName, "before", before, ct);
                await DacpacDeployer.DeployFromFileAsync(
                    beforeDacpac, ConnectionString, targetDbName, cancellationToken: ct);

                // Seed data so we can prove it survives the identity change.
                await using (var seedConn = await OpenAsync(targetDbName, ct))
                {
                    await ExecuteAsync(seedConn, seedSql, ct);
                }

                // Deploy the changed schema to the same database.
                var afterDacpac = await BuildDacpacAsync(tempDir.FullName, "after", after, ct);
                var result = await DacpacDeployer.DeployFromFileAsync(
                    afterDacpac, ConnectionString, targetDbName, options: afterOptions,
                    cancellationToken: ct);

                var script = result.Script ?? string.Empty;

                if (expectChanges)
                {
                    Assert.True(result.WasExecuted);
                    Assert.False(string.IsNullOrWhiteSpace(script),
                        "An identity change should generate a non-empty script.");
                }

                // The database's model must now match the changed DACPAC's model.
                Model afterModel;
                await using (var stream = File.OpenRead(afterDacpac))
                {
                    (_, afterModel) = await DacpacSerializer.Deserialize(stream, ct);
                }

                var deployedModel = await provider
                    .CreateDatabaseModelBuilder(createdDb)
                    .ExtractModelAsync(ct);

                Assert.Equal(
                    ModelAssertions.ElementHashMultiset(afterModel),
                    ModelAssertions.ElementHashMultiset(deployedModel));

                // Run the scenario-specific data and script assertions.
                await using var conn = await OpenAsync(targetDbName, ct);
                await assertAfterAsync(conn, script);
            }
            finally
            {
                await createdDb.DropAsync(ct);
            }
        }
        finally
        {
            tempDir.Delete(recursive: true);
        }
    }

    // 'a' = GENERATED ALWAYS, 'd' = GENERATED BY DEFAULT, '' = not an identity column.
    // attidentity is Postgres's internal "char" type, so it is cast to text to come back as a
    // string rather than a .NET char.
    private static async Task<string?> AttidentityAsync(
        NpgsqlConnection conn, string table, string column)
        => (string?)await ScalarAsync(conn, $"""
SELECT attidentity::text FROM pg_attribute
WHERE attrelid = '{table}'::regclass AND attname = '{column}';
""");

    // The column's stored DEFAULT expression, or null when it has none. A serial column carries a
    // nextval(...) default; an identity column does not.
    private static async Task<string?> ColumnDefaultAsync(
        NpgsqlConnection conn, string table, string column)
        => (string?)await ScalarAsync(conn, $"""
SELECT pg_get_expr(d.adbin, d.adrelid)
FROM pg_attrdef d
JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE d.adrelid = '{table}'::regclass AND a.attname = '{column}';
""");

    // The increment and maximum of the sequence backing an identity/serial column, read from
    // pg_sequence via the column's owned sequence.
    private static async Task<(long Increment, long Max)> OwnedSequenceOptionsAsync(
        NpgsqlConnection conn, string table, string column)
    {
        var increment = await ScalarAsync(conn, $"""
SELECT s.seqincrement FROM pg_sequence s
JOIN pg_class c ON c.oid = s.seqrelid
WHERE c.oid = pg_get_serial_sequence('{table}', '{column}')::regclass;
""");

        var max = await ScalarAsync(conn, $"""
SELECT s.seqmax FROM pg_sequence s
JOIN pg_class c ON c.oid = s.seqrelid
WHERE c.oid = pg_get_serial_sequence('{table}', '{column}')::regclass;
""");

        Assert.NotNull(increment);
        Assert.NotNull(max);

        return (Convert.ToInt64(increment), Convert.ToInt64(max));
    }

    private static Task<string> BuildDacpacAsync(
        string dir, string label, string schema, CancellationToken ct)
        => DacpacTestBuilder.BuildToFileAsync(
            dir, schema, "Postgresql",
            ws => new ParserWorkspaceModelBuilder(ws, new AntlrPostgresParser()),
            ct, label: label, outputSubdirectory: "bin", fileName: label);

    private async Task<NpgsqlConnection> OpenAsync(string databaseName, CancellationToken ct)
    {
        var connectionString = new NpgsqlConnectionStringBuilder(ConnectionString)
        {
            Database = databaseName
        }.ConnectionString;

        var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync(ct);
        return conn;
    }

    private static async Task ExecuteAsync(NpgsqlConnection conn, string sql, CancellationToken ct)
    {
        await using var cmd = new NpgsqlCommand(sql, conn);
        await cmd.ExecuteNonQueryAsync(ct);
    }

    private static async Task<object?> ScalarAsync(NpgsqlConnection conn, string sql)
    {
        await using var cmd = new NpgsqlCommand(sql, conn);
        return await cmd.ExecuteScalarAsync(TestContext.Current.CancellationToken);
    }
}
