CREATE TABLE authors
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    email varchar(255)
);

CREATE TABLE books
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    author_id integer NOT NULL REFERENCES authors (id)
);

CREATE INDEX idx_books_author ON books (author_id);
