using Squill.PostgresParser.Syntax;

namespace Squill.PostgresParser;

public partial class PostgresVisitor
{
    public override SyntaxNode VisitColconstraintelem(PostgreSQLParser.ColconstraintelemContext context)
    {
        if (context.NULL_P() is not null)
        {
            return new NullableColumnConstraint(context.GetText(), context.NOT() is null);
        }

        if (context.PRIMARY() is not null && context.KEY() is not null)
        {
            // TODO: support opt_definition and optconsttablespace
            return new PrimaryKeyColumnConstraint(context.GetText());
        }

        if (context.DEFAULT() is not null)
        {
            if (VisitB_expr(context.b_expr()) is not Expression expression)
            {
                throw new PostgresParseException("Expected an Expression for DEFAULT constraint");
            }

            return new DefaultColumnConstraint(context.GetText(), expression);
        }

        if (context.REFERENCES() is not null)
        {
            if (VisitQualified_name(context.qualified_name()) is not QualifiedName referencedTable)
            {
                throw new PostgresParseException("Unable to parse REFERENCES target table");
            }

            // opt_column_list on an inline reference names a single referenced column;
            // omitting it defaults to the referenced table's primary key.
            var referencedColumns = ParseOptColumnList(context.opt_column_list());

            if (referencedColumns.Count > 1)
            {
                throw new PostgresParseException(
                    "An inline column REFERENCES clause may reference at most one column");
            }

            var (onDelete, onUpdate) = ParseKeyActions(context.key_actions());

            return new ForeignKeyColumnConstraint(
                context.GetText(),
                referencedTable,
                referencedColumns.Count == 1 ? referencedColumns[0] : null,
                onDelete,
                onUpdate);
        }

        if (context.GENERATED() is not null && context.IDENTITY_P() is not null)
        {
            // GENERATED ALWAYS AS IDENTITY vs GENERATED BY DEFAULT AS IDENTITY. The
            // optparenthesizedseqoptlist (START, INCREMENT, ...) is parsed but not
            // modeled yet (see follow-up issue).
            var always = context.generated_when().ALWAYS() is not null;

            return new IdentityColumnConstraint(context.GetText(), always);
        }

        // TODO: support UNIQUE, CHECK, and GENERATED ... AS (expr) STORED
        throw new NotImplementedException("Column constraint type not yet implemented");
    }
}