using Squill.PostgresParser.Syntax;

namespace Squill.PostgresParser;

public partial class PostgresVisitor
{
    public override SyntaxNode VisitColconstraintelem(PostgreSQLParser.ColconstraintelemContext context)
    {
        if (context.NULL_P() is not null)
        {
            return new NullableColumnConstraint(context.GetText(), context.NOT() is null);
        }

        if (context.PRIMARY() is not null && context.KEY() is not null)
        {
            // TODO: support opt_definition and optconsttablespace
            return new PrimaryKeyColumnConstraint(context.GetText());
        }

        if (context.DEFAULT() is not null)
        {
            if (VisitB_expr(context.b_expr()) is not Expression expression)
            {
                throw new PostgresParseException("Expected an Expression for DEFAULT constraint");
            }

            return new DefaultColumnConstraint(context.GetText(), expression);
        }

        if (context.REFERENCES() is not null)
        {
            if (VisitQualified_name(context.qualified_name()) is not QualifiedName referencedTable)
            {
                throw new PostgresParseException("Unable to parse REFERENCES target table");
            }

            // opt_column_list on an inline reference names a single referenced column;
            // omitting it defaults to the referenced table's primary key.
            var referencedColumns = ParseOptColumnList(context.opt_column_list());

            if (referencedColumns.Count > 1)
            {
                throw new PostgresParseException(
                    "An inline column REFERENCES clause may reference at most one column");
            }

            var (onDelete, onUpdate) = ParseKeyActions(context.key_actions());

            return new ForeignKeyColumnConstraint(
                context.GetText(),
                referencedTable,
                referencedColumns.Count == 1 ? referencedColumns[0] : null,
                onDelete,
                onUpdate);
        }

        if (context.GENERATED() is not null && context.IDENTITY_P() is not null)
        {
            // GENERATED ALWAYS AS IDENTITY vs GENERATED BY DEFAULT AS IDENTITY, with an
            // optional parenthesized sequence-option list (issue #13).
            var always = context.generated_when().ALWAYS() is not null;

            long? startValue = null, increment = null, minValue = null, maxValue = null, cacheSize = null;
            bool? cycle = null;

            if (context.optparenthesizedseqoptlist()?.seqoptlist() is { } seqoptlist)
            {
                foreach (var option in seqoptlist.seqoptelem())
                {
                    if (option.NO() is not null)
                    {
                        // NO MAXVALUE / NO MINVALUE select the default bound — the same
                        // meaning as omitting the option — so only NO CYCLE is recorded.
                        if (option.CYCLE() is not null)
                        {
                            cycle = false;
                        }
                    }
                    else if (option.CYCLE() is not null)
                    {
                        cycle = true;
                    }
                    else if (option.START() is not null)
                    {
                        startValue = ParseSequenceNumber(option);
                    }
                    else if (option.INCREMENT() is not null)
                    {
                        increment = ParseSequenceNumber(option);
                    }
                    else if (option.MINVALUE() is not null)
                    {
                        minValue = ParseSequenceNumber(option);
                    }
                    else if (option.MAXVALUE() is not null)
                    {
                        maxValue = ParseSequenceNumber(option);
                    }
                    else if (option.CACHE() is not null)
                    {
                        cacheSize = ParseSequenceNumber(option);
                    }
                    else
                    {
                        // AS <type>, OWNED BY, SEQUENCE NAME, RESTART — not valid (or not
                        // meaningful) on a declarative identity column.
                        throw new NotImplementedException(
                            $"Identity sequence option '{option.GetText()}' is not supported");
                    }
                }
            }

            return new IdentityColumnConstraint(context.GetText(), always,
                startValue, increment, minValue, maxValue, cacheSize, cycle);
        }

        // TODO: support UNIQUE, CHECK, and GENERATED ... AS (expr) STORED
        throw new NotImplementedException("Column constraint type not yet implemented");
    }

    // The integer value of a sequence option (START WITH n, INCREMENT BY n, ...). The
    // numericonly text includes any sign and no whitespace; sequence options are integral,
    // so a non-integer (float) value is rejected.
    private static long ParseSequenceNumber(PostgreSQLParser.SeqoptelemContext option)
    {
        var text = option.numericonly()?.GetText()
            ?? throw new PostgresParseException(
                $"Expected a numeric value for sequence option '{option.GetText()}'");

        if (!long.TryParse(text, System.Globalization.NumberStyles.AllowLeadingSign,
                System.Globalization.CultureInfo.InvariantCulture, out var value))
        {
            throw new PostgresParseException(
                $"Sequence option value '{text}' is not a valid integer");
        }

        return value;
    }
}