using Squill.PostgresParser.Syntax;

namespace Squill.PostgresParser.Tests;

public class CreateTableIdentityTests
{
    [Fact]
    public void GeneratedByDefaultAsIdentity()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);
        Assert.Equal("id", idColumn.Name.Name);

        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());
        Assert.False(identity.Always);
    }

    [Fact]
    public void GeneratedAlwaysAsIdentity()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED ALWAYS AS IDENTITY
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);

        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());
        Assert.True(identity.Always);
    }

    [Fact]
    public void IdentityCombinedWithPrimaryKey()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);

        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());
        Assert.False(identity.Always);
        Assert.Single(idColumn.Constraints.OfType<PrimaryKeyColumnConstraint>());
    }

    private static CreateTableStatement ParseSingleCreateTable(AntlrPostgresParser parser, string text)
    {
        var root = parser.Parse(text);

        Assert.NotNull(root);
        Assert.Single(root.Statements);

        return Assert.IsType<CreateTableStatement>(root.Statements[0]);
    }
}
