using Squill.PostgresParser.Syntax;

namespace Squill.PostgresParser.Tests;

public class CreateTableIdentityTests
{
    [Fact]
    public void GeneratedByDefaultAsIdentity()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);
        Assert.Equal("id", idColumn.Name.Name);

        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());
        Assert.False(identity.Always);
    }

    [Fact]
    public void GeneratedAlwaysAsIdentity()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED ALWAYS AS IDENTITY
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);

        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());
        Assert.True(identity.Always);
    }

    [Fact]
    public void IdentityCombinedWithPrimaryKey()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);

        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());
        Assert.False(identity.Always);
        Assert.Single(idColumn.Constraints.OfType<PrimaryKeyColumnConstraint>());
    }

    [Fact]
    public void IdentityWithFullSequenceOptions()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5 MINVALUE 100 MAXVALUE 9999 CACHE 10 CYCLE)
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);
        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());

        Assert.False(identity.Always);
        Assert.Equal(100L, identity.StartValue);
        Assert.Equal(5L, identity.Increment);
        Assert.Equal(100L, identity.MinValue);
        Assert.Equal(9999L, identity.MaxValue);
        Assert.Equal(10L, identity.CacheSize);
        Assert.True(identity.Cycle);
    }

    [Fact]
    public void IdentityWithNegativeIncrementAndNoOptions()
    {
        var parser = new AntlrPostgresParser();

        // NO MAXVALUE / NO MINVALUE select the defaults (same as omitting the option);
        // NO CYCLE is an explicit no-cycle. A signed numericonly must parse.
        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED ALWAYS AS IDENTITY (INCREMENT BY -1 NO MAXVALUE NO MINVALUE NO CYCLE)
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);
        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());

        Assert.True(identity.Always);
        Assert.Equal(-1L, identity.Increment);
        Assert.Null(identity.StartValue);
        Assert.Null(identity.MinValue);
        Assert.Null(identity.MaxValue);
        Assert.Null(identity.CacheSize);
        Assert.False(identity.Cycle);
    }

    [Fact]
    public void IdentityWithoutOptions_HasNoSequenceOptions()
    {
        var parser = new AntlrPostgresParser();

        const string text = """
CREATE TABLE widgets
(
    id integer GENERATED BY DEFAULT AS IDENTITY
);
""";

        var createTable = ParseSingleCreateTable(parser, text);

        var idColumn = Assert.IsType<ColumnDefinition>(createTable.Elements[0]);
        var identity = Assert.Single(idColumn.Constraints.OfType<IdentityColumnConstraint>());

        Assert.Null(identity.StartValue);
        Assert.Null(identity.Increment);
        Assert.Null(identity.MinValue);
        Assert.Null(identity.MaxValue);
        Assert.Null(identity.CacheSize);
        Assert.Null(identity.Cycle);
    }

    private static CreateTableStatement ParseSingleCreateTable(AntlrPostgresParser parser, string text)
    {
        var root = parser.Parse(text);

        Assert.NotNull(root);
        Assert.Single(root.Statements);

        return Assert.IsType<CreateTableStatement>(root.Statements[0]);
    }
}
